Wetflame_TLDR_0001:
		dc.w	(Wetflame_TLDR_0001_END-Wetflame_TLDR_0001-2)/40
		dc.b	"             Programs used              "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"             Tile Molester              "
		dc.b	"                                        "
		dc.b	"               by SnowBro               "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                SonMapEd                "
		dc.b	"                                        "
		dc.b	"              by Xenowhirl              "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                HivePal                 "
		dc.b	"                                        "
		dc.b	"              by Hivebrain              "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                XM3SMPS                 "
		dc.b	"                                        "
		dc.b	"          by Nineko & Oerg866           "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                XM4SMPS                 "
		dc.b	"                                        "
		dc.b	"                by Puto                 "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"               S1SMPS2ASM               "
		dc.b	"                                        "
		dc.b	"               by Cinossu               "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"            ImaGenesis 4000             "
		dc.b	"                                        "
		dc.b	"               by DevSter               "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"        The Sega Data Compressor        "
		dc.b	"                                        "
		dc.b	"                by Magus                "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"      Sonic 1 Text Code Generator       "
		dc.b	"                                        "
		dc.b	"                by Selbi                "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
@MUSIC:		dc.b	"               Music used               "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"             Title Screen:              "
		dc.b	"                                        "
		dc.b	" Sonic Unleashed - Endless Possibility  "
		dc.b	"                                        "
		dc.b	"                                        "
                dc.b	"                                        "
		dc.b	"           Intro Cutscene:              "
		dc.b	"                                        "
		dc.b	"   Ninja Gaiden 1 - Intro Cutscene 2    "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"        Final Stand Cutscene:           "
		dc.b	"                                        "
		dc.b	"   Ninja Gaiden 1 - The Masked Devil    "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"         Sunset Plains Zone 1:          "
		dc.b	"                                        "
		dc.b	"      DM Ashura - Radix Run Zone        "
		dc.b	"                                        "
		dc.b	"         SMPS port by Cinossu           "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"          Sunset Plains Zone 2:         "
		dc.b	"                                        "
		dc.b	"    Jurassic Boy 2 [NES] - World 1-1    "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"          Sunset Plains Zone 3:         "
		dc.b	"                                        "
		dc.b	"        Ninja Gaiden 1 - Act 4-2        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"           Mutant Ship Zone 3:          "
		dc.b	"                                        "
		dc.b	"  AVGN Adventures - Future F***balls    "
		dc.b	"                                        "
		dc.b	"               2010 Stage               "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"              Final Stand :             "
		dc.b	"                                        "
		dc.b	" Sonic 3 & Knuckles - The Doomsday Zone "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"               Act Clear:               "
		dc.b	"                                        "
		dc.b	"     Knuckles Chaotix - Act Clear       "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"               All Clear:               "
		dc.b	"                                        "
		dc.b	"     Gunstar Heroes - Stage Clear       "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"           Ending & Credits:            "
		dc.b	"                                        "
		dc.b	"     Dangerous Seed - Ending Theme      "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"            Special Stage:              "
		dc.b	"                                        "
		dc.b	"  Mario & Sonic at the Olympic Games    "
		dc.b	"                                        "
		dc.b	"   (Beijing 2008) - Circuit Results     "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
@OTHERCRDT:	dc.b	"             Other Credits              "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                HCKTROX                 "
		dc.b	"                                        "
		dc.b	"      Game mode array optimization      "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"          Sonic65 & GerbilSoft          "
		dc.b	"                                        "
		dc.b	"      Part of Sonic 1 WTFLAME's code    "
		dc.b	"                                        "
		dc.b	"      (Wetflame TL;DR and The Game as   "
		dc.b	"                                        "
		dc.b	"             end credits roll)          "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"               Hivebrain                "
		dc.b	"                                        "
		dc.b	"        Sonic 1 2005 disassembly        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"               MarkeyJester             "
		dc.b	"                                        "
		dc.b	"            Fading routine fix          "
		dc.b	"                                        "
		dc.b	"             PCM table handler          "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"               JMAN2050                 "
		dc.b	"                                        "
		dc.b	"  Uncompressed PCM playback Z80 Driver  "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"             Original game              "
		dc.b	"                                        "
		dc.b	"         by SEGA & Sonic Team           "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"   SAM THE RABBIT (c)2013-2015 Sam237   "
		dc.b	"                                        "
		dc.b	" sonicfanchara.wikia.com/Sam_the_rabbit "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"  SONIC THE HEDGEHOG (c)1991-2015 SEGA  "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"                                        "
		dc.b	"           Presented by Zy BG9K         "
		dc.b	"                                        "
		dc.b	"         -Sonic Fan Character Wiki-     "
		even
Wetflame_TLDR_0001_END: